version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: appointment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: appointment_pass
      POSTGRES_DB: appointment_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
